### PR TITLE
Update dataset

### PR DESCRIPTION
**Pull request by karolpiczak**

### CODE REVIEW

**Comment by mansur61** [comment]
What does A,B mean in dataset? Can you explain

**Comment by karolpiczak** [comment]
Some longer source recordings from Freesound were split into more than one audio event (WAV file in the dataset). In this case they are denoted by alphabet letters, e.g.:

```
1-101296-A-19.wav
1-101296-B-19.wav
```

Those are two distinct sound examples extracted from the Freesound clip 101296 (which is originally 12 min in length). The sound examples are different, but they share the recording characteristics (same device, conditions).

**Comment by mansur61** [comment]
Hi,
Thanks for your explanation. But it would be very nice if the baby's crying
sound was known. Do you have data in this way? If found, can you share?
Besat regards

Karol J. Piczak ***@***.***>, 1 Şub 2022 Sal, 14:24 tarihinde
şunu yazdı:

**Comment by karolpiczak** [comment]
I am sorry, but your question isn't clear. What kind of information do you want to retrieve?

**Comment by mansur61** [comment]
Do you have only the sound data of baby sounds from Esc-50 sound data?
Can you share if found?


4 Şub 2022 Cum 18:09 tarihinde Karol J. Piczak ***@***.***>
şunu yazdı:

**Comment by karolpiczak** [comment]
All the files ending in -20.WAV are "baby crying" sounds. You can try
searching Freesound.org for more content of this type.

**Comment by mansur61** [comment]
thanks, but are baby crying sounds tagged? so for example it's like crying
for hunger

4 Şub 2022 Cum 19:21 tarihinde Karol J. Piczak ***@***.***>
şunu yazdı:

**Comment by karolpiczak** [comment]
No information of this kind is available in the dataset.

**Comment by mansur61** [comment]
Hi,
How many kbps are your datasets?
Regards.

Karol J. Piczak ***@***.***>, 4 Şub 2022 Cum, 19:44 tarihinde
şunu yazdı:

**Comment by karolpiczak** [comment]
All recordings are 44.1 kHz WAV files, but they were generated from various
source recordings with possibly different audio settings.

**Pull request merged**
